#!/bin/bash
echo -n "Afficher uniquement le login, l'UID et le Path de chaque entree du fichier /etc/psswd Y/N ? "
read answr
if [ "$answr" = "y" ] || [ "$answr" = "Y" ]; then
	echo "login		  UID	  Path :"
	cat /etc/passwd | awk -F  ":" '{print $1 "   " $3 "   " $6}' | column -t
elif [ "$answr" = "n" ] || [ "$answr" = "N" ]; then
	echo "Soit"
else
	echo "Apprends a lire"
fi
