#!/bin/bash
echo -n "Voulez-vous afficher uniquement le login, l'UID et le Path de chaque entree du fichier /etc/psswd Y/N ? "
read ouinon
if [ "$ouinon" = "y" ] || [ "$ouinon" = "Y" ]; then
	echo "login		  UID	  Path :"
	cat /etc/passwd | awk -F  ":" '{print $1 "   " $3 "   " $6}' | column -t
elif [ "$ouinon" = "n" ] || [ "$ouinon" = "N" ]; then
	echo "Ok, bye !"
else
	echo "omae ma wou shindeiru. nani $ouinon"
fi
