#!/bin/bash
echo "Quel utilisateur veux tu supprimer ?"
read usr
id -u "$usr"> /dev/null 2>&1
if [ "$?" == "0" ]; then
	sudo userdel -rf $usr
	echo "$usr deleted"
else
	echo "$usr does not exist"
fi

#http://lanterne-rouge.over-blog.org/article-que-signifie-dev-null-2-1-70233357.html
